### ISSUE TITLE
New MVC5 Web API template doesn't build

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FSharpCommunityTemplates#51]
If I create a new Web API project from the latest template on the Visual Studio Gallery, I have the following problems:
- [ ] Newtonsoft.Json reference is broken
- [ ] I get the following error when I try to build:

```
Error   1   The "MSBuild.ExtensionPack.FileSystem.File" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Windows\Microsoft.NET\Framework\v4.0.30319" directory.    C:\Users\Ryan\Code\frank\samples\AspNet\AspNet.fsproj   162 5   AspNet
```

**Comment by frankhale** [comment]
I have this issue right now using the latest version of the F# MVC project template. This happened after I updated all of the NuGet packages on a clean project template (no additional code added beyond what the template provides).

```
The "MSBuild.ExtensionPack.FileSystem.File" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\MSBuild\12.0\bin" directory.
```

**Comment by frankhale** [comment]
I had to change the following like in the fsproj file so that it uses the correct version of MSBuild.Extension.Pack:

```
<UsingTask AssemblyFile="$(SolutionDir)\packages\MSBuild.Extension.Pack.1.5.0\tools\net40\MSBuild.ExtensionPack.dll" TaskName="MSBuild.ExtensionPack.FileSystem.File" />
```

**Comment by panesofglass** [comment]
Now that [FSharp.Core](http://www.nuget.org/packages/FSharp.Core) is available on NuGet (in a sane way), I think we should drop MSBuild.Extension.Pack and just use that NuGet package. It will also allow projects built in VS to run in Xamarin Studio. I'll try to tackle this tomorrow.

**Comment by hoonzis** [comment]
I am still having this issue using the MVC 5 F# template, has anything changed? Changing the project file manually fixes the problem (updating the version for the Extension.Pack). The nuget package, should probably take care of this? I am using paket to update nuget and the dll can be found here:

```
$(SolutionDir)\packages\MSBuild.Extension.Pack\tools\net40\MSBuild.ExtensionPack.dll
```

**Comment by SabrinaMH** [comment]
I also ran into this issue and needed to modify the lines in the fsproj files to
`$(SolutionDir)\packages\MSBuild.Extension.Pack.1.3.0\tools\net40\MSBuild.ExtensionPack.dll`
