### ISSUE TITLE
Visual Studio 2015 preview / MVC 5 templates

### ISSUE THREAD

**Issue by frankhale** [fsprojects/FSharpCommunityTemplates#86]
I have VS 2013 with MVC 5 templates installed. I wanted to also install those templates for VS 2015 but if I run the installer it tells me that I already have the templates installed. I'm guessing that the installer does not recognize that I have both VS 2013 and VS 2015 preview installed. Ideally I'd like to install MVC 5 templates in VS 2015. For now I'll just create my projects in VS 2013 and then open them up in VS 2015.

**Comment by dmohl** [comment]
This has been fixed and is now available on VSG in version 1.12.

**Comment by frankhale** [comment]
Awesome! Thank you so much!!!
