### ISSUE TITLE
Visual Studio 2015 preview / Web Item Templates

### ISSUE THREAD

**Issue by frankhale** [fsprojects/FSharpCommunityTemplates#87]
I installed the Web Item Templates extension from the Visual Studio Gallery in VS 2015 preview but after installation the web item templates don't show up in the dialog when trying to add new items to the project.

https://visualstudiogallery.msdn.microsoft.com/f1dae7fe-1ecc-4f1b-86b5-32a2970d012a

**Comment by dmohl** [comment]
This is now supported and available in verion 3.1.

**Comment by frankhale** [comment]
Thank you!
