### ISSUE TITLE
Add jquery.validate to F# MVC project template

### ISSUE THREAD

**Issue by frankhale** [fsprojects/FSharpCommunityTemplates#90]
I'd be nice if the F# MVC project template included jquery validate so that it's as easy to validate forms on the client side as it is in C#. It's not a huge deal to add it in by hand but since the C# template comes with it I think the F# one should as well.

**Comment by frankhale** [comment]
As an aside to this issue, over the last few days I've been porting the C# based template for ASP.NET MVC 5 with individual login accounts to F#. I've got all the code ported now and I've been using this as a learning gateway to get more into F#. While I have not made this into a generic Visual Studio template it may be useful for a larger audience. If you have time I would greatly appreciate any thoughts you have on the code and/or ways to make it better. I'm sure that there are some better more idiomatic F# ways to spice the code up. While it's not 100% tested all the up front features seem to work nicely (eg, running the website, clicking on the controller actions, registering a user, logging in,  etc..).

https://github.com/frankhale/FSharpASPNETMVC

**Comment by panesofglass** [comment]
Very cool! Thanks! I'm still new to converting things to templates, but I think this would be a good one to migrate.

For more on F# style, you may find the following of interest:

* [TodoBackend](http://todobackend.com/)
* [TodoBackendFSharp](https://github.com/panesofglass/TodoBackendFSharp) ([related slides for a related talk](http://panesofglass.github.io/TodoBackendFSharp))
* [Web Machine for F#](https://github.com/freya-fs/freya.examples)

**Comment by frankhale** [comment]
Thank you so much Ryan! I'll definitely check those suggestions out!!!

**Comment by frankhale** [comment]
Closing this for now, if there is any interest feel free to reopen.
